markdown: redcarpet
higlighter: pygments
exclude: ["LICENSE.txt", "README.md"]

baseurl: ""
permalink: /:title/

paginate: 1
paginate_path: "/pagination/page:num/"

gems:
  - jekyll-multiple-languages-plugin
  - jekyll-paginate
  - jekyll-admin

languages: ["en", "ru"]

title: "Max Strakhov Data Science Blog"
description: "Blog about data science and machine learning"
url: "https://realzoberg.github.io"
timezone: Europe/Moscow
future: false
exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]
#jekyll_admin:
#  hidden_links:
#    - posts
#    - pages
#    - staticfiles
#    - datafiles
#    - configuration
